/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sedanur
 */
public class gecis extends javax.swing.JFrame {

    /**
     * Creates new form gecis
     */
    public gecis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnrezervasyonkayit = new javax.swing.JButton();
        btnpersonelkayit = new javax.swing.JButton();
        btnmusterikayit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        btncikis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTEL OTOMASYONU");

        jPanel1.setLayout(null);

        btnrezervasyonkayit.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        btnrezervasyonkayit.setText("REZERVASYON KAYIT");
        btnrezervasyonkayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrezervasyonkayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnrezervasyonkayit);
        btnrezervasyonkayit.setBounds(270, 110, 160, 50);

        btnpersonelkayit.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        btnpersonelkayit.setText("PERSONEL KAYIT");
        btnpersonelkayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonelkayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnpersonelkayit);
        btnpersonelkayit.setBounds(360, 40, 140, 50);

        btnmusterikayit.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        btnmusterikayit.setText("MÜŞTERİ KAYIT");
        btnmusterikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusterikayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnmusterikayit);
        btnmusterikayit.setBounds(210, 40, 140, 50);

        jTree1.setBackground(new java.awt.Color(234, 191, 147));
        jTree1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("OTEL");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("MÜŞTERİ");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MÜŞTERİ KAYIT");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("PERSONEL");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("PERSONEL KAYIT");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("REZERVASYON");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REZERVASYON KAYIT");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 200, 210);

        jToolBar1.setRollover(true);

        btncikis.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        btncikis.setText("ÇIKIŞ");
        btncikis.setFocusable(false);
        btncikis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncikis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncikisActionPerformed(evt);
            }
        });
        jToolBar1.add(btncikis);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(466, 180, 60, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/depositphotos_64518047-stock-photo-beautiful-flowers-backgrounds.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 524, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncikisActionPerformed
        dispose();
    }//GEN-LAST:event_btncikisActionPerformed

    private void btnmusterikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusterikayitActionPerformed
        gecis ana_ekran = new gecis();
        ana_ekran.setVisible(false);
        setVisible(false);
        musterikayit frame = new musterikayit();
        frame.setVisible(true);
    }//GEN-LAST:event_btnmusterikayitActionPerformed

    private void btnpersonelkayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonelkayitActionPerformed
        gecis ana_ekran = new gecis();
        ana_ekran.setVisible(false);
        setVisible(false);
        personel frame = new personel();
        frame.setVisible(true);
    }//GEN-LAST:event_btnpersonelkayitActionPerformed

    private void btnrezervasyonkayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrezervasyonkayitActionPerformed
        gecis ana_ekran = new gecis();
        ana_ekran.setVisible(false);
        setVisible(false);
        rezervasyon frame = new rezervasyon();
        frame.setVisible(true);
    }//GEN-LAST:event_btnrezervasyonkayitActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        String node = evt.getNewLeadSelectionPath().getLastPathComponent().toString();
        if( node.equals("MÜŞTERİ KAYIT") ) {
          musterikayit anaframe=new musterikayit();
          anaframe.setVisible(true);
        } else if( node.equals("PERSONEL KAYIT") ) {
          personel anaframe=new personel();
          anaframe.setVisible(true);
        }
        else if(node.equals("REZERVASYON KAYIT")){
            rezervasyon anaframe=new rezervasyon();
            anaframe.setVisible(true);
        }
    }//GEN-LAST:event_jTree1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gecis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gecis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gecis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gecis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gecis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncikis;
    private javax.swing.JButton btnmusterikayit;
    private javax.swing.JButton btnpersonelkayit;
    private javax.swing.JButton btnrezervasyonkayit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
